services:
  pastebin:
    tty: true
    stdin_open: true
    image: pastebin:latest
    container_name: pastebin
    volumes:
      - ./config:/config
      - ./files:/files
    restart: always
    network_mode: host
#    ports:
#      - 80:80
 
